# Generated by Django 5.2.8 on 2026-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
